name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches: [main]

jobs:
  setup:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: [9.6.3]
    runs-on: ${{ matrix.os }}
    name: Setup ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/latest-hwm
        with:
          ghc: ${{ matrix.ghc }}

      # Build ONLY dependencies. If this succeeds, the cache is SAVED.
      - name: Install dependencies
        shell: bash
        run: stack build --fast --test --only-dependencies

  build:
    needs: setup
    strategy:
      matrix:
        include:
          - ghc: 9.6.3
            env: stable
      fail-fast: false
    runs-on: ubuntu-latest
    name: GHC ${{ matrix.ghc }} (${{ matrix.env }})
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/latest-hwm
        with:
          ghc: ${{ matrix.ghc }}

      - name: Build
        run: stack build --fast

      - name: Test
        run: stack test --fast

  archive:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Artifact ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/latest-hwm
      - name: Test Archiving
        shell: bash
        run: hwm release artifacts

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: curl -sSL https://raw.githubusercontent.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL "https://raw.githubusercontent.com/nalchevanidze/hwm/main/scripts/format.sh" | bash -s

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
