name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - ghc: 9.6.3
            env: default
          # - ghc: 8.10.7
          #   env: legacy
      fail-fast: false
    runs-on: ubuntu-latest
    name: GHC ${{ matrix.ghc }} (${{ matrix.env }})
    steps:
      - uses: actions/checkout@v4
      - uses: nalchevanidze/hwm/actions/ghc@main
        with:
          ghc: ${{ matrix.ghc }}
      
      - name: Sync environment
        run: hwm sync ${{ matrix.env }}

      - name: Install dependencies
        run: stack build --fast --skip-ghc-check --no-terminal --test --only-dependencies

      - name: Build
        run: stack build --fast

      - name: Test
        run: stack test --fast

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lint
        run: curl -sSL https://raw.githubusercontent.com/ndmitchell/hlint/master/misc/run.sh | sh -s .

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL "https://raw.githubusercontent.com/nalchevanidze/hwm/main/scripts/format.sh" | bash -s

  artifacts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Artifact ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nalchevanidze/hwm/actions/ghc@main

      - name: Binary
        uses: nalchevanidze/hwm/actions/pkg@main
        with:
          package: hwm
          executable: hwm
          smoke_test: version

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
